version: '3.8'

services:
  # Servicio de base de datos SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - basketball-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1'"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s

  # Servicio de la API de Basketball
  basketball-api:
    build:
      context: ./BasketballScoreboardAPI
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=BasketballScoreboardDB;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - basketball-network

  # Servicio del frontend Angular
  basketball-frontend:
    build:
      context: ./basketball-scoreboard
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - basketball-api
    networks:
      - basketball-network

networks:
  basketball-network:
    driver: bridge

volumes:
  sql_data:
